### ISSUE TITLE
Collect resource owners (applications/teams)

### ISSUE THREAD

**Issue by hjacobs** [hjacobs/kube-resource-report#3]
Assume a certain structure of pod labels to identify resource owners. The ``application`` or ``app`` label should point to a valid application ID. An optional application registry (REST service) can provide additional information about the owning team.

**Comment by hjacobs** [comment]
First version was implemented: one HTML page is generated for every team: 
![screenshot-2018-6-3 team cat - kubernetes resource report](https://user-images.githubusercontent.com/510328/40889101-16096f1e-6761-11e8-81fd-64dd90fd2f96.png)

**Comment by avietrov** [comment]
Would it make sense to add a fallback to "owner" label (e.g. expect "owner: team/foobar"), since not all pods are applications registered, like for example if you deploy redis with your app.

**Comment by hjacobs** [comment]
@avietrov a fallback sounds good, but in your case I would also label the Redis StatefulSet with the same `application` label if it belongs to your application. I added a `component` label to distinguish between `frontend` (Deployment) and `redis` (StatefulSet) The same should apply to PostgreSQL databases and similar (not sure how the [Zalando PostgreSQL Operator](https://github.com/zalando-incubator/postgres-operator) does it).

**Comment by avietrov** [comment]
Makes sense. I guess I thought about the `application` label in a wrong way: instead of having the same label between identical resources, the label is for every resource within the same system. For example if we run a web server for ui, a master node and a pool of slave nodes all of them should have `application=foo` but different `component=master` or `component=webserver` instead of `application=foo-master`, `application=foo-webserver`.

**Comment by hjacobs** [comment]
Closing this for now as the application ownership (team) already works.
